name: Deploy Frontend
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Iniciando despliegue..."
            # 1. Instalar Git si no existe (por seguridad)
            sudo dnf install git -y
            
            # 2. Clonar el repo si no existe, o actualizar si ya está
            if [ ! -d "Front_EVAL2" ]; then
              git clone https://github.com/Martin89899/Front_EVAL2.git
            fi
            
            cd Front_EVAL2
            git pull origin main
            
            # 3. Levantar con Docker (Corregido para Amazon Linux 2023)
            sudo docker compose up -d --build
